### ISSUE TITLE
orderByDeps doesn't allow relative dependencies

### ISSUE THREAD

**Issue by Tantalon** [jamiebuilds/workspaces-run#4]
orderByDeps only works if there is a semver match between the dependency and version in package.json

In a npm multi-module project, I use something like this to depend upon other modules:
```
"dependencies": {
 "module-b": "file:../module-b"
}
```

This isn't a semver match, so the modules run in the wrong order.

Is there a better way of doing these references?

**Comment by jamiebuilds** [comment]
I think this is just a matter of updating the `getWorkspaceGraph` function to support that in addition to semver.

https://github.com/jamiebuilds/workspaces-run/blob/c3fa2d215a247a41946f579671ded5687f58f445/src/utils/workspaces.ts#L60-L104

**Comment by Tantalon** [comment]
Thanks I've raised PR https://github.com/jamiebuilds/workspaces-run/pull/5 to do this.
